import os

env_content = """# Flask Configuration
FLASK_APP=app.py
FLASK_ENV=production
SECRET_KEY=your-secret-key-here

# Database Configuration
MYSQL_HOST=localhost
MYSQL_USER=fedbryan
MYSQL_PASSWORD=your-mysql-password
MYSQL_DATABASE=fedbryan$kishanx

# API Keys
ALPHA_VANTAGE_API_KEY=YTEHGJP4RCYRYW7G
ALPHA_VANTAGE_BACKUP_KEY=XKXHZXU8QXQX6LB9
OPENEXCHANGERATES_API_KEY=d16db1e03711417581ce5a2dda273830
CURRENCYLAYER_API_KEY=9e46ca5a5edd08e5592cb1779e9dc05d
FIXER_API_KEY=9e46ca5a5edd08e5592cb1779e9dc05d

# Angel One API Credentials
ANGEL_ONE_API_KEY=your_angel_one_api_key_here
ANGEL_ONE_CLIENT_CODE=your_angel_one_client_code_here
ANGEL_ONE_PASSWORD=your_angel_one_password_here
ANGEL_ONE_TOTP_SECRET=your_angel_one_totp_secret_here

# API Settings
API_TIMEOUT=10
CACHE_DURATION=1
PREMIUM_API_ENABLED=false
MAX_RETRIES=3

# Rate Limiting
ALPHA_VANTAGE_RATE_LIMIT=5
ALPHA_VANTAGE_DAILY_LIMIT=25
EXCHANGERATE_API_RATE_LIMIT=5
FIXER_RATE_LIMIT=5
OPENEXCHANGERATES_RATE_LIMIT=5
CURRENCYLAYER_RATE_LIMIT=5

# Cache Settings
PRICE_CACHE_DURATION=300
HISTORICAL_CACHE_DURATION=3600

# Error Handling
MAX_CONSECUTIVE_ERRORS=3
ERROR_RETRY_DELAY=5
ENABLE_ERROR_LOGGING=true

# Trading Settings
DEFAULT_TIMEFRAME=1m
DEFAULT_VOLUME_THRESHOLD=100000
DEFAULT_SPREAD_THRESHOLD=1.5

# Risk Management
MAX_POSITION_SIZE=0.02
MAX_DAILY_TRADES=10
MAX_DAILY_LOSS=0.05
STOP_LOSS_PERCENTAGE=0.02
TAKE_PROFIT_PERCENTAGE=0.04

# Signal Generation
SIGNAL_CONFIDENCE_THRESHOLD=0.75
MIN_VOLUME_THRESHOLD=100000
MAX_SPREAD_THRESHOLD=1.5
REQUIRED_CONFIRMATIONS=2

# OTC Settings
OTC_VOLUME_THRESHOLD=150000
OTC_SPREAD_THRESHOLD=1.0
OTC_MIN_ACCURACY=0.75
OTC_REQUIRED_CONFIRMATIONS=3

# WebSocket Configuration
WEBSOCKET_HOST=localhost
WEBSOCKET_PORT=8765

# Logging
LOG_LEVEL=INFO
LOG_FORMAT="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
LOG_FILE=trading_app.log
"""

# Write the content to .env file
with open('.env', 'w') as f:
    f.write(env_content)

print("Created .env file successfully!") 