name: Deploy Flask Trading Application

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libmysqlclient-dev build-essential pkg-config
        # Install TA-Lib from source
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib/
        ./configure --prefix=/usr
        make
        sudo make install
        cd ..
        rm -rf ta-lib ta-lib-0.4.0-src.tar.gz

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        
        # Install core numerical packages first
        pip install "numpy==1.23.5" "pandas==1.5.3" "scipy==1.10.1" "scikit-learn==1.3.0"
        
        # Install pandas_ta from GitHub (working version for Python 3.10)
        pip install "git+https://github.com/twopirllc/pandas-ta.git@0.3.14"
        
        # Install remaining packages from requirements.txt
        pip install -r requirements.txt --use-deprecated=legacy-resolver

    - name: Verify critical installations
      run: |
        python -c "
        try:
            import pandas as pd; print(f'✓ Pandas: {pd.__version__}')
            import numpy as np; print(f'✓ Numpy: {np.__version__}')
            import flask; print(f'✓ Flask: {flask.__version__}')
            import pandas_ta; print(f'✓ pandas_ta: {pandas_ta.__version__}')
            import talib; print('✓ TA-Lib: OK')
            import yfinance; print('✓ yfinance: OK')
            import smartapi; print('✓ SmartAPI: OK')
            import mysql.connector; print('✓ MySQL Connector: OK')
            print('✓ All critical packages installed successfully')
        except ImportError as e:
            print(f'✗ Import Error: {e}')
            exit(1)
        except Exception as e:
            print(f'✗ Error: {e}')
            exit(1)
        "

    - name: Run basic tests
      env:
        MYSQL_HOST: localhost
        MYSQL_PORT: 3306
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: test_db
        FLASK_ENV: testing
      run: |
        python -c "
        # Test basic imports
        import pandas as pd
        import numpy as np
        import flask
        from flask_cors import CORS
        import mysql.connector
        import pandas_ta
        import talib
        import yfinance as yf
        from smartapi import SmartConnect
        print('All imports successful!')
        "
        echo "Basic functionality test passed!"

    - name: Build and deploy
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        echo "Building application..."
        # Add your build commands here

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        enable_jekyll: false
        keep_files: true
